services:
  catalogservice:
    container_name: catalogservice
    image: ${DOCKER_REGISTRY-}catalogservice
    build:
      context: .
      dockerfile: CatalogService/Dockerfile
    ports:
      - "8000:8080"

  orderservice:
    container_name: orderservice
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    ports:
      - "9000:8080" 

  apigateway:
    container_name: apigateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "7000:8080"
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"